wandb_version: 1

gamma:
  desc: null
  value: 0.95
lr:
  desc: null
  value: 0.005
batch_size:
  desc: null
  value: 32
eps:
  desc: null
  value: 1.0
eps_decay:
  desc: null
  value: 0.995
eps_min:
  desc: null
  value: 0.01
max_update_steps:
  desc: null
  value: 100
total_ep:
  desc: null
  value: 10000
info_decay:
  desc: null
  value: 0.5
buffer_size:
  desc: null
  value: 50000
trainstart_buffersize:
  desc: null
  value: 10000
_wandb:
  desc: null
  value:
    python_version: 3.8.18
    cli_version: 0.15.8
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1700061284.45961
    t:
      1:
      - 1
      - 55
      - 77
      3:
      - 16
      - 23
      4: 3.8.18
      5: 0.15.8
      8:
      - 5
