wandb_version: 1

gamma:
  desc: null
  value: 0.95
lr:
  desc: null
  value: 0.005
batch_size:
  desc: null
  value: 32
eps:
  desc: null
  value: 0.99
eps_decay:
  desc: null
  value: 0.995
eps_min:
  desc: null
  value: 0.01
max_update_steps:
  desc: null
  value: 100
total_ep:
  desc: null
  value: 10000
info_decay:
  desc: null
  value: 0.5
buffer_size:
  desc: null
  value: 50000
trainstart_buffersize:
  desc: null
  value: 10000
book_decay:
  desc: null
  value: 0.8
map_size:
  desc: null
  value: 20
predator1_view_range:
  desc: null
  value: 8
predator2_view_range:
  desc: null
  value: 3
n_predator1:
  desc: null
  value: 5
n_predator2:
  desc: null
  value: 5
n_prey:
  desc: null
  value: 5
_wandb:
  desc: null
  value:
    python_version: 3.8.18
    cli_version: 0.16.0
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1701408193.341783
    t:
      1:
      - 1
      - 55
      - 77
      2:
      - 1
      - 55
      - 77
      3:
      - 16
      - 17
      - 23
      - 37
      4: 3.8.18
      5: 0.16.0
      8:
      - 5
      13: linux-x86_64
